### ISSUE TITLE
能否日历添加年份的选择

### ISSUE THREAD

**Issue by zsjabjj** [nan1010082085/VueComponents#2]
![微信图片_20190520175244](https://user-images.githubusercontent.com/32876943/58012925-1f90c380-7b28-11e9-9451-0f2a6bab0d31.png)
类似图片中的样式, 可以切换年月

**Comment by zsjabjj** [comment]
其实是想做一个事件日历, 有事件的加点表示, 被选中的日子圈圈起来

**Comment by nan1010082085** [comment]
都可以的啊， 我有暴露出选中状态， 小圆点状态， 也有点击事件

**Comment by nan1010082085** [comment]
@zsjabjj  ![image](https://user-images.githubusercontent.com/26052449/59003197-8829b100-8847-11e9-8ef9-496d69e2ac16.png)
这个组件是可以支持你要的功能的， 不过样式还有其他的一些事件添加需要自己根据业务处理

**Comment by zsjabjj** [comment]
好的, 我先试试, 有什么不懂的再来请教, 谢谢

**Comment by nan1010082085** [comment]
![image](https://user-images.githubusercontent.com/26052449/59005605-e1e2a900-8850-11e9-8001-c6d678dbcc0a.png)
![image](https://user-images.githubusercontent.com/26052449/59005621-e909b700-8850-11e9-9a6c-dc9e9174234b.png)
关于年月的切换需要根据上图的这个三个方法来算， 并且根据你传入的数据来展示那个日期需要是选中状态

**Comment by zsjabjj** [comment]
好的, 万分感谢, 我先做起来, 这个搁置有段时间了, 哈哈
