### ISSUE TITLE
AddressList

### ISSUE THREAD

**Issue by xbo729** [nan1010082085/VueComponents#9]
能否拖动省市县的时候即为选中，省去点击这一步操作

**Comment by nan1010082085** [comment]
当时这个是实现，但是在在适配的时候有一些位置处理的问题，所以放弃了拖动选中

**Comment by xbo729** [comment]
还有就是你这个是一次性加载所有数据&nbsp; 能不能做成分段加载方式&nbsp; 比如省市县联动问题 3级联动 数据量就是4w调&nbsp; 如果4级联动。前端可能会奔溃。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yangdongnan"<notifications@github.com&gt;; 
发送时间: 2020年3月4日(星期三) 中午12:02
收件人: "nan1010082085/VueComponents"<VueComponents@noreply.github.com&gt;; 
抄送: "心说"<834554220@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nan1010082085/VueComponents] AddressList (#9)




当时这个是实现，但是在在适配的时候有一些位置处理的问题，所以放弃了拖动选中

**Comment by xbo729** [comment]
而且在开发中遇见了input 输入框聚焦输入&nbsp; 移动端下面的键盘弹出&nbsp; &nbsp;这个是没问题的&nbsp; &nbsp;但是隐藏后&nbsp; 会出现无法定位到输入框的位置（当然这个问题移动端都存在这个问题，能否在插件中 聚焦的时候 配置属性设置位置补偿&nbsp; 也就是滚动条定位的功能）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yangdongnan"<notifications@github.com&gt;; 
发送时间: 2020年3月4日(星期三) 中午12:02
收件人: "nan1010082085/VueComponents"<VueComponents@noreply.github.com&gt;; 
抄送: "心说"<834554220@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nan1010082085/VueComponents] AddressList (#9)




当时这个是实现，但是在在适配的时候有一些位置处理的问题，所以放弃了拖动选中

**Comment by nan1010082085** [comment]
> 还有就是你这个是一次性加载所有数据&nbsp; 能不能做成分段加载方式&nbsp; 比如省市县联动问题 3级联动 数据量就是4w调&nbsp; 如果4级联动。前端可能会奔溃。。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yangdongnan"<notifications@github.com&gt;; 发送时间: 2020年3月4日(星期三) 中午12:02 收件人: "nan1010082085/VueComponents"<VueComponents@noreply.github.com&gt;; 抄送: "心说"<834554220@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [nan1010082085/VueComponents] AddressList (#9) 当时这个是实现，但是在在适配的时候有一些位置处理的问题，所以放弃了拖动选中 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

其实这个不是一次性渲染的， 你在接口调用的时候是可以控制的， 一列一列加载， 但是我写的这个可能有些复杂，在渲染上应该问题不大。

**Comment by nan1010082085** [comment]
感谢同学提出的问题，但是重写可能是一个耗时的工程，由于现在工作项目问题，应该不会考虑修改了
